Added a check for Word or Excel macros to the OfficeMRUs command
GhostPack/Seatbelt pull request #64
Opened 2020-12-28 22:06 UTC by jahawkins

Example execution below:

![image](https://user-images.githubusercontent.com/7451600/103245617-57780380-4926-11eb-8092-8afdc9087394.png)

2021-01-11 19:23 UTC, leechristensen commented on Seatbelt/Commands/Products/OfficeMRUsCommand.cs
> +                    if (vbomKey.GetValueNames().Contains("AccessVBOM"))
On my test machine, the "AccessVBOM" key does not exist by default.  Can you create this value if it does not exist, and delete it later?

2021-01-11 19:30 UTC, leechristensen commented on Seatbelt/Commands/Products/OfficeMRUsCommand.cs
> +                composedFile = comp.Name + Environment.NewLine;
One of our goals is to have structured output everywhere we can. This violates that since you're outputting the Module Name + the macro in the same text block.  Could you return a custom Module object instead with two properties (Name + MacroCode or something)

2021-01-11 19:32 UTC, leechristensen requested changes
Added a couple of comments. Besides those, things look good! Thanks for the contribution!

2021-01-16 03:33 UTC, jahawkins commented on Seatbelt/Commands/Products/OfficeMRUsCommand.cs
> +                    if (vbomKey.GetValueNames().Contains("AccessVBOM"))
Good point, overlooked that test. Should be fixed in 4df9e19e712e94bdc06c65fa0c8b3f184e56f533.

2021-01-16 03:35 UTC, jahawkins commented on Seatbelt/Commands/Products/OfficeMRUsCommand.cs
> +                composedFile = comp.Name + Environment.NewLine;
Created a class for the Macro objects to break out module name and code into separate fields and updated the formatting of the output. Updated in 4df9e19e712e94bdc06c65fa0c8b3f184e56f533.

2021-01-16 03:36 UTC, jahawkins commented
Updated the csproj file as well to have absolute paths to the interop DLLs in an additional commit.

2021-01-20 09:54 UTC, leechristensen approved these changes

2021-01-20 09:56 UTC, leechristensen commented
@jahawkins Changes look good! I just so happened to have a password protected .xls on my test machine and when this module runs it actually opens Excel up on the desktop displaying the password prompt and locks Seatbelt until it's closed. 

Any chance you could account for this?

2021-01-20 12:05 UTC, jahawkins commented
I had a similar situation where I had a macro that popped up a message box. I'll look into the COM instantiation and see if there are options to either check for these ahead of time or to open in more of a protected mode.

2023-03-07 17:00 UTC, A9G-Data-Droid commented
I'm dropping in to say that it is not safe to open malicious office files. Autorun could infect the system you are attempting to analyze. You don't even have a call to suppress Autorun which would look like this:

```
excelApp.EnableEvents = false;
```

Although that would help I don't recommend that being the solution. I would recommend using a tool to extract the VBA code without opening the file in a host capable of running the code.

This can be done with the `olevba` tool found here:
[olevba](https://github.com/decalage2/oletools/wiki/olevba)

2024-01-06 00:36 UTC, leechristensen commented
Closing due to age and outstanding issue.

2024-01-06 00:36 UTC, closed without merging